//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcIsTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Personel()
        {
            this.Isler = new HashSet<Isler>();
            this.Yetkiler = new HashSet<Yetkiler>();
        }
    
        public int PersonelID { get; set; }
        public string PersonelAd { get; set; }
        public Nullable<int> PersonelBirimID { get; set; }
        public string KullaniciAd { get; set; }
        public string PersonelParola { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Isler> Isler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yetkiler> Yetkiler { get; set; }
    }
}
